apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJiV0Z6YUd0MWMzUTZaMmh3WDJGdFZsVldVV1UxZDNSdWF6bFpRMWxETUVvMU5qVnliMUZEUm1SNVVERk9ha2MxVUE9PSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
